apiVersion: batch/v1
kind: Job
metadata:
  generateName: nats-message-sender-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: nats-message-sender
    spec:
      containers:
      - name: message-sender
        image: arm32v6/nats:2.8.4-alpine3.15
        command: ["bash", "-c", "nats-pub my-subject 'Your message'"] # Modify with your NATS server URL, subject name, and message
      restartPolicy: Never
